<?php $_config_vars = array (
  'MesOnPage' => '10',
  'ComOnPage' => '10',
  'PhotoOnPage' => '15',
  'NLOnPage' => '20',
  'NLOverview' => '10',
  'lmyblog' => 'page.php?mod=blog',
  'lmyphoto' => 'page.php?mod=photo',
  'notspecified' => 'Not specified',
  'tfeedback' => 'Contact Us',
  'temail' => 'Your Email',
  'tfirstname' => 'First Name',
  'tlastname' => 'Last Name',
  'tmessage' => 'Message',
  'tsend' => 'Send',
  'totherway' => 'Please click <a href="index.php?mod=page&pn=contacts">here</a> for other ways to contact us!',
  'isreq' => 'is required!',
  'iswrong' => 'is wrong!',
  'textmail' => '
                        E-mail: %email%
                        First name: %firstname%
                        Last name:  %lastname%
                        Message: %message%
                        Date: %date%
                        ',
  'sendok' => 'Message sent!',
  'display' => 'Displaying',
  'of' => 'of',
  'page' => 'Page',
  'items' => 'items',
  'sortby' => 'Sort by',
  'search' => 'Search',
  'notfound' => 'Messages not found',
  'errnfound' => 'Element not found',
  'comments' => 'comments',
  'comment' => 'comment',
  'nocomments' => 'No comments',
  'add_comment' => 'Add a new comment',
  'new_review' => 'New review',
  'add_message' => 'Add Comment',
  'add_new_message' => 'Add a blog entry',
  'reply' => 'Reply to this',
  'wrote' => 'wrote on',
  'pfrom' => 'From',
  'psubject' => 'Subject',
  'pmessage' => 'Message',
  'post_it' => 'Post it',
  'fpost' => 'posted on',
  'my_photo' => 'My Photos',
  'tblog' => 'Blog',
  'tnightlife' => 'Nightlife',
  'tculture' => 'Culture',
  'tfood' => 'Food',
  'tlodging' => 'Lodging',
  'tnecessities' => 'Necessities',
  'delete_mes' => 'Delete message with all comments?',
  'delete_com' => 'Delete commentary?',
  'mes_del' => 'Message deleted',
  'com_del' => 'Commentary deleted',
  'delimage' => 'Delete image',
  'delete' => 'Delete',
  'image' => 'Image',
  'bcancel' => 'Cancel',
  'bsubmit' => 'Submit',
  'tdelete' => 'Delete',
  'tback' => 'Back to',
  'delete_img' => 'Delete photo with all comments?',
  'img_del' => 'Image deleted',
); ?>